### ISSUE TITLE
Invalid response from NTP server error

### ISSUE THREAD

**Issue by chonamdoo** [instacart/truetime-android#19]
public class PrivacyCall extends MultiDexApplication {
         public void onCreate() {

                 TrueTimeRx.build()
                           .withConnectionTimeout(31_428)
                           .withRetryCount(3)
                           .initialize(ntpHosts)
                           .subscribeOn(Schedulers.io())
                           .subscribe();
         }
java.lang.RuntimeException: Invalid response from NTP server. Root delay violation 9153
     at com.instacart.library.truetime.extensionrx.TrueTimeRx$2$2.call(TrueTimeRx.java:60)
     at com.instacart.library.truetime.extensionrx.TrueTimeRx$2$2.call(TrueTimeRx.java:50)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
     at rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:200)
     at rx.internal.util.ScalarSynchronousObservable$2$1.call(ScalarSynchronousObservable.java:114)
     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:761)
 Caused by: java.lang.RuntimeException: Invalid response from NTP server. Root delay violation 9153
     at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:111)
     at com.instacart.library.truetime.extensionrx.TrueTimeRx$2$2.call(TrueTimeRx.java:56)
 	... 12 more
 Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: 1.us.pool.ntp.org
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
 	... 10 more

**Comment by kaushikgopal** [comment]
yup, as per the (S)NTP protocol, this is totally a possibility. suggestions:

* shoot the request to more than a single host (by default we only query one host) how many hosts are you initializing (in `ntpHosts` i.e.)
* bump up the `retryCount` from 3 to probably around 10 (or 20). once we've triangulated a request, we don't issue re-requests, so there isn't necessarily a cost to increasing that retry count.

closing this one out, cause this is an expected occurrence. feel free to open if you feel otherwise.

**Comment by consp1racy** [comment]
Done and done. Still no good.

I wouldn't call not being able to initialize the damn thing "an expected occurrence". 

What's root delay violation and how do I fix it?

**Comment by kaushikgopal** [comment]
:). k so a couple of things:

> I wouldn't call not being able to initialize the damn thing "an expected occurrence".
> What's root delay violation and how do I fix it?

Unfortunately, such is the way of NTP. there are times when the result is not accurate and if the result is not accurate, then it's more dangerous to claim that a time is accurate and send it down vs. not provide it all. yup it's frustrating that initialization hasn't occurred, but that only means you have to keep retrying. that's how the [NTP spec](https://tools.ietf.org/html/rfc5905) works.

as per the super informative yet abstruse [NTP spec](https://tools.ietf.org/html/rfc5905) spec again, there are times where the NTP server you poll can return faulty results (building on the previous point). why does this happen? well some of the NTP servers are public and literally you and i can setup a local NTP server on a Mac mini in our basements. We can register and have it included in a legit NTP server pool. If I start sending crazy times from my Mac mini NTP server, then we have to have a way of filtering those results out in the library. the NTP spec specifies how that can be done. one of those many checks is "root delay violation". 

There are a whole bunch of validation checks that we run to filter erroneous responses. For a list of all the other checks, have a look at [this part of the code](https://github.com/instacart/truetime-android/blob/master/library/src/main/java/com/instacart/library/truetime/SntpClient.java#L137).
