### ISSUE TITLE
Expected SNTP time from last boot to be cached. couldn't find it.

### ISSUE THREAD

**Issue by AlexLardschneider** [instacart/truetime-android#34]
Hello,
lately I added the TrueTime library in my app, but some clients encounter an issue with it crashing, because of the reason written in the title.

Stacktrace:
```
Caused by java.lang.RuntimeException: expected SNTP time from last boot to be cached. couldn't find it.
       at com.instacart.library.truetime.TrueTime._getCachedSntpTime(Unknown Source)
       at com.instacart.library.truetime.TrueTime.now(Unknown Source)
       at com.example.data.Handler$1.call(Unknown Source)
       at rx.internal.operators.OnSubscribeFromCallable.call(Unknown Source)
       at rx.internal.operators.OnSubscribeFromCallable.call(Unknown Source)
       at rx.Observable.create(Unknown Source)
       at rx.internal.operators.OperatorSubscribeOn$1.call(Unknown Source)
       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(Unknown Source)
       at rx.internal.schedulers.ScheduledAction.run(Unknown Source)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Before accessing `TrueTime.now()` I check if TrueTime is available using `TrueTimeRx.isInitialized()`, which returns true.

I load TrueTime like follows if it is not initialized yet (`TrueTime.isInitialized()` returns false):

```java
TrueTimeRx.build()
                .withLoggingEnabled(false)
                .withSharedPreferences(context)
                .initializeRx("time.apple.com")
                .subscribeOn(Schedulers.io())
                .subscribe(new Observer<Date>() {
                    @Override
                    public void onCompleted() {
                    }

                    @Override
                    public void onError(Throwable e) {
                        Timber.v(e, "Could not get TrueTime");
                    }

                    @Override
                    public void onNext(Date date) {
                        Date deviceDate = new Date();
                        long drift = date.getTime() - deviceDate.getTime();
                        Timber.e("TrueTime=%s, local=%s, dif=%s", date, deviceDate, drift);
                    }
                });
```

According to the documents this should be the correct way to use TrueTime, isn't it?
The issue only happens on 6.0.1 (That's what Crashlytics is telling me at least), and only on Samsung devices.

Am I doing something wrong, or is this an issue with the library? Looking through the source code of the library I cannot find something obvious which can lead to this error, so I can't come up with a way to prevent this from happening. Any help would be appreciated.

Best regards,
Alex

**Comment by rpattabi** [comment]
I am new to true time (or Rx for that matter). However it looks like, it is a bug with working with the cached time. Avoiding `withSharedPreferences(context)` is probably a quick workaround. Also enabling this option may require permission to run on boot. Not sure if your app has that permission.

@AlexLardschneider Curious to know if / how you made progress from this crash.

**Comment by kaushikgopal** [comment]
hmm..

The disk cache uses `SharedPreferences` which definitely doesn't require any additional permission. the only permission required is the network permission which gets added at the library level.

> Before accessing TrueTime.now() I check if TrueTime is available using TrueTimeRx.isInitialized(), 

@AlexLardschneider + @rpattabi : i suspect the issue might be with `TrueTime.now()` vs `TrueTimeRx.now()`. You should be using the Rx variant for `now`, if you're truly using TrueTimeRx for the initialization.

I notice there's an error in the sample app too, where we incorrectly refer to `TrueTime.now` in the Rx sample. let me know if that solves the issue

**Comment by kaushikgopal** [comment]
@AlexLardschneider closing this, cause i'm hopeful that would solve the problem. if you're still seeing an issue, please feel free to reopen this issue

**Comment by AlexLardschneider** [comment]
Hello @kaushikgopal,

correct me if I'm wrong, but doesn't calling `TrueTimeRx.now()` indirectly call `TrueTime.now()`, as the class `TrueTimeRx` does not implement the method `now()`? So calling `TrueTime.now()` or `TrueTimeRx.now()` should always produce the same output, right?

**Comment by lion-not-swim** [comment]
forceInitializeRx()
