### ISSUE TITLE
InvalidNtpServerResponseException

### ISSUE THREAD

**Issue by vg0426** [instacart/truetime-android#38]
Hi i just downloaded this project to see it in action cause i try to run it in my project and i was getting an error but the same error is showing in your project when i click the "GET THE TIME NOW" button:

**E/SampleActivity: Exception when trying to get TrueTime
                  com.instacart.library.truetime.InvalidNtpServerResponseException: Server response delay too large for comfort 142
                      at com.instacart.library.truetime.SntpClient.requestTime(SntpClient.java:171)
                      at com.instacart.library.truetime.TrueTime.requestTime(TrueTime.java:89)
                      at com.instacart.library.truetime.TrueTime.initialize(TrueTime.java:85)
                      at com.instacart.library.truetime.TrueTime.initialize(TrueTime.java:49)
                      at com.instacart.library.sample.SampleActivity$InitTrueTimeAsyncTask.doInBackground(SampleActivity.java:75)
                      at com.instacart.library.sample.SampleActivity$InitTrueTimeAsyncTask.doInBackground(SampleActivity.java:65)
                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)**

**Comment by consp1racy** [comment]
Why this happens:
https://github.com/instacart/truetime-android#troubleshootingexception-handling

How to solve it:
https://github.com/instacart/truetime-android#rx-ified-version

>What is nifty about the Rx version?
>
> * as against just SNTP, you get full NTP (read: far more accurate time)
> * the NTP pool address you provide is resolved into multiple IP addresses
> * we query each IP multiple times, guarding against checks, and taking the best response
> * if any one of the requests fail, we retry that failed request (alone) for a specified number of times
> * we collect all the responses and again filter for the best result as per the NTP spec

I used it successfully like so:

        val NTP_HOSTS = listOf("time.apple.com",
                "europe.pool.ntp.org",
                "north-america.pool.ntp.org")

        TrueTimeRx.build()
                .initialize(NTP_HOSTS)
                .subscribeOn(Schedulers.io())
                .subscribe(object : Subscriber<Date>() {
                    override fun onError(e: Throwable) {
                        te(e) { "TrueTime not available." }
                    }

                    override fun onNext(t: Date) {
                        val i = Instant.ofEpochMilli(t.time)
                        tw { "TrueTime has a date: $i" }
                    }

                    override fun onCompleted() {
                    }
                })

**Comment by kaushikgopal** [comment]
@vg0426 exactly what @consp1racy said. another issue was opened similarly and has the details. closing this one out now.
