### ISSUE TITLE
RX implementation may leak exceptions on eg. network issues

### ISSUE THREAD

**Issue by masc3d** [instacart/truetime-android#98]
we occasionally see this exception terminating our application.
it seems like it's leaking from the internal flowables.

```
Uncaught exception [Thread[RxCachedThreadScheduler-5,5,main]] The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | Network is unreachable
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | Network is unreachable
	at io.reactivex.plugins.RxJavaPlugins.a(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.a(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.b_(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.b_(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.b_(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.b_(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.c(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.g(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.b(Unknown Source)
	at com.instacart.library.truetime.TrueTimeRx$4$1$2.a(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableCreate.b(Unknown Source)
	at io.reactivex.Flowable.a(Unknown Source)
	at io.reactivex.Flowable.a(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(Unknown Source)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.io.IOException: Network is unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:694)
...
```

**Comment by thearaks** [comment]
I'm experiencing many `UndeliverableException`s too for the same reasons

**Comment by DjangoLC** [comment]
@masc3d 
I there i was the same problem and found the solution, in my case i was making the next code: 
.subscribe(allRouteData -> {
                            allRouteData.forEach(item-> Log.e(TAG, "load: "+item.getName()));
                        }, error-> Log.e(TAG, "loadAllAddress error: "+error.getMessage())));

the problem is this line (allRouteData.forEach(item-> Log.e(TAG, "load: "+item.getName()));) once a just make a simple for each the error disappear, forEach is available in api 24 or higher

**Comment by nooballday** [comment]
It happened to me aswell, but the weird thing is that it only happens in released apk, when i debug it its running fine.

**Comment by masc3d** [comment]
> It happened to me aswell, but the weird thing is that it only happens in released apk, when i debug it its running fine.

it's not really weird, as different / slower timings in debug builds may cause lower probability for this to happen. 

I refined error handler above, which is the correct solution for this issue.
